### ISSUE TITLE
Cached global statics

### ISSUE THREAD

**Issue by Andarist** [mridgway/hoist-non-react-statics#44]
I'm a little bit unsure why this is needed:
```js
var defineProperty = Object.defineProperty;
var getOwnPropertyNames = Object.getOwnPropertyNames;
var getOwnPropertySymbols = Object.getOwnPropertySymbols;
var getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
var getPrototypeOf = Object.getPrototypeOf;
var objectPrototype = getPrototypeOf && getPrototypeOf(Object);
```

Are those property lookups considered costful so they are cached? By inlining them we could save 34 bytes (checked on minified and gzipped bundle)

**Comment by mridgway** [comment]
I wouldn't say they are costful, but it is certainly more efficient at runtime to cache them AFAIK. This is a common pattern in React as well: https://github.com/facebook/react/blob/72434a7686035b4af766ee7d06c070d7f5d6a5f2/packages/shared/shallowEqual.js#L12

I don't plan on changing this currently since 34 bytes does not seem worthwhile.
