### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by maxaggedon** [mridgway/hoist-non-react-statics#47]
I see that typescript types consider that the source component and the target should share the same props. But I often use this module with components that have completely different props (because several HoC enhance the source component).

Shouldn't the type declaration allow for source and target to have no props in common ? like so:

```
function hoistNonReactStatics<Own, Custom>(
    TargetComponent: React.ComponentType<Own>,
    SourceComponent: React.ComponentType<Custom>,
    customStatic?: any): React.ComponentType<Own>;
```

**Comment by dobesv** [comment]
https://github.com/mridgway/hoist-non-react-statics/pull/56

**Comment by mridgway** [comment]
I will be removing the type definitions from the package in favor of using DefinitelyTyped so that I will not need to own maintenance of the type definition. Because of this I will not be merging any additional changes to the type definitions in this repository.

See https://github.com/mridgway/hoist-non-react-statics/issues/53
