### ISSUE TITLE
latest 2.5.1 and 2.5.2 version break react-apollo

### ISSUE THREAD

**Issue by ppasmanik** [mridgway/hoist-non-react-statics#52]
Looks like both 2.5.1 and 2.5.2 versions break react-apollo.

    at IncomingMessage.g (events.js:292:16) TypeError: hoistNonReactStatics$1 is not a function
    at eval (webpack:///./node_modules/react-apollo/react-apollo.browser.umd.js?:962:20)
    at eval (webpack:///./node_modules/react-apollo/node_modules/lodash/_createFlow.js?:68:42)

It works properly with 2.5.0

**Comment by mridgway** [comment]
What version of typescript are you using? I'm beginning to think it is impossible to keep a type definition in the codebase that works with all versions of typescript.

**Comment by mridgway** [comment]
@dawnmist same question for you since you made the change to the export.

**Comment by dphrag** [comment]
Also broke here. My code base is not typescript. Same error as above. Breaks react-apollo.

**Comment by mridgway** [comment]
Reverted and published 2.5.3.

**Comment by dtaub** [comment]
I tried 2.5.3, still running into the same issue. It completely breaks the app.

I'm also really confused as to why that's the case. Looking at the commit history it looks like only TypeScript typedefs changed, which I didn't think should affect non-typescript users.

The only other change I see is to the `files` array in package.json.

**Comment by mridgway** [comment]
Looking into this still. Going to pin `latest` to 2.5.0 for now.

**Comment by mridgway** [comment]
I have a suspicion that it may be the new `module: "src/index.js` entry in the package.json that is triggering this for you. Could someone try removing that in their node_modules and trying again?

**Comment by mridgway** [comment]
I have not been able to reproduce this. If anyone has a simple repro case, please let me know so that I can debug further.

**Comment by dawnmist** [comment]
The reason I made the change to the typescript definition was because the definitions did not permit using the default import. It generates this error instead:
![image](https://user-images.githubusercontent.com/5810277/41187005-ad627dec-6be4-11e8-9e06-d2554a921e79.png)

It should not have affected anything not using typescript in any way.

**Comment by dawnmist** [comment]
The other thing that has changed since 2.5.0 is a new build system to publish in multiple forms - https://github.com/mridgway/hoist-non-react-statics/commit/03a7f2f87ae9d9a41696b2a7f109aa1aab6b9eab
![image](https://user-images.githubusercontent.com/5810277/41187102-49850df6-6be6-11e8-9f14-3ed637a63cbe.png)

I suspect that the issues is more to do with the changes to how the release is compiled/packaged than anything else.

**Comment by dawnmist** [comment]
@dtaub If you modify the hoist-non-react-statics package.json file and change main to "dist/hoist-non-react-statics.js" (instead of ending with '.cjs.js') are you able to compile/load the app? I think that looks like it's the equivalent compiled module type to what the 2.5.0 release contained. Just trying to help identify what change actually did cause the issue.

**Comment by pedrokermitgoncalves** [comment]
Hi guys! Do you have an ETA on when would this be solved?

I added this resolutions to my package.json in order to solve the problem 
`  "resolutions": {
    "hoist-non-react-statics": "2.5.0"
  }`
but would be nice to trust the dependency updating again

**Comment by mridgway** [comment]
I was able to confirm through the referenced issue in react-click-outside that it was related to `module: src/index.js`. I have removed that entry and published a new version.

Please try it out and let me know if you still see the issue.

**Comment by c316** [comment]
Yay! That fixed it for me.

**Comment by danilobuerger** [comment]
@mridgway since the issue was not related to the fix by @dawnmist do you mind reverting your revert?

**Comment by mridgway** [comment]
@danilobuerger I reverted the revert and published v2.5.5.

**Comment by danilobuerger** [comment]
awesome, thanks @mridgway !
