### ISSUE TITLE
types Declaration is es6 modules but package.json main field is cjs file

### ISSUE THREAD

**Issue by Onlylonger** [mridgway/hoist-non-react-statics#54]
types Declaration is es6 modules but package.json main field is cjs  file

version: '2.5.5'

![image](https://user-images.githubusercontent.com/19505200/41806794-c08ccab8-76f6-11e8-87f6-6796ffde8884.png)

---

![image](https://user-images.githubusercontent.com/19505200/41806797-c89a897a-76f6-11e8-9a95-346b43834fd3.png)

**Comment by mridgway** [comment]
I will be removing the type definitions from the package in favor of using DefinitelyTyped so that I will not need to own maintenance of the type definition. Because of this I will not be merging any additional changes to the type definitions in this repository.

See https://github.com/mridgway/hoist-non-react-statics/issues/53
