### ISSUE TITLE
Keeping isReactComponent prototype

### ISSUE THREAD

**Issue by danbovey** [mridgway/hoist-non-react-statics#59]
Hi

I'm currently experiencing an issue passing a HOC directly to another component that is expecting the React Component to have `.prototype.isReactComponent` available. The HOC is [react-intl](https://github.com/yahoo/react-intl/blob/master/src/inject.js) and it's using this package to clone a WrappedComponent. The prototype property is [added by React](https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js#L31) to allow others to easily check if a function is a React Component, which is used by [react-table](https://github.com/react-tools/react-table/blob/master/src/utils.js#L208).

Seeing as this package is cloning React components, should this one prototype property be cloned too?

This current fix is to add this manaully before exporting:

```js
const injected = injectIntl(MyComponent);
injected.prototype.isReactComponent = {};

export default injected
```

**Comment by mridgway** [comment]
Since this is a react specific property and not a static, I don't think it's right for this library to be hoisting it.

With that said, I don't see any reason why that property would not be available on an instance of the component since `injectIntl` is using a class that extends `React.Component` which defines that property. 

I would also suggest not using that property on the prototype since it is subject to change as per [Dan Abramov](https://twitter.com/dan_abramov/status/787739945301635073).
