### ISSUE TITLE
Drop React <16.0.0 support?

### ISSUE THREAD

**Issue by oliviertassinari** [mridgway/hoist-non-react-statics#67]
Looking at https://github.com/styled-components/styled-components/pull/2021, it seems that dropping React <16.0.0 support can reduce the bundle size.

**Comment by mridgway** [comment]
On first glance, I can't tell what changes were made to the file since it also contains a lot of other changes (ES6 modules, prettier, etc.). I did end up removing some ES6 syntax to make the code smaller when transpiled with babel.

I am not in favor of dropping support for less that React 16 at this time since it would create a lot of churn in the community with all the libraries that are currently using hoisting.

**Comment by oliviertassinari** [comment]
Would it make sense to consult the styled-components' team to see what could be improved here, and have them used this library? :)

**Comment by mridgway** [comment]
Commented on the PR mentioned above.

**Comment by mridgway** [comment]
Looks like @eps1lon already put in the effort here: https://github.com/styled-components/styled-components/pull/2265

Not worth pushing further on this imo.

**Comment by oliviertassinari** [comment]
@mridgway Thank you for looking at it!
