### ISSUE TITLE
Why not supported copy static defaultProps, displayName?

### ISSUE THREAD

**Issue by s-kobets** [mridgway/hoist-non-react-statics#79]
I use
```javascript
function(WrappedComponent) {
  class Component extends PureComponent {
      ....
  }

  return hoistNonReactStatics(Component, WrappedComponent);
}
```

**Comment by aarondancer** [comment]
Solution:

```
function(WrappedComponent) {
  class Component extends PureComponent {
      ....
  }

  const Hoisted = hoistNonReactStatics(Component, WrappedComponent);
  
  Hoisted.defaultProps = WrappedComponent.defaultProps;

  return Hoisted;
}
```

**Comment by s-kobets** [comment]
I am that and doing, but I think that can doing `hoistNonReactStatics`, if I can that create merge request.

**Comment by mridgway** [comment]
I don't think this is always the desired behavior for HoCs. I'd prefer to keep this out of the library and have a user land solution like @aarondancer posted.

**Comment by salmanm** [comment]
While it makes sense that it might not be always desired to copy the `defaultProps`. But the way I see it is when we wrap a component, it makes sense for the wrapper to receive the same props as the original component would receive if it were not wrapped. This could be important for so many reasons I think. For instance when an HoC wants to act based on a prop value but it didn't just because it didn't exist.

A more realistic example would be an HoC calling `react-jss` and there we get only user specified props but not the complete props after merging with `defaultProps`.

Of course I'm not suggesting we should copy `defaultProps` by default, but we could probably have a fourth parameter say `whitelist` that let's user pass whatever they need. 

If this sounds good, I'd be happy to PR that.
